version: '3.8'

services:
  metawalletgen:
    build: .
    image: metawalletgen/cli:2.0.0
    container_name: metawalletgen-cli
    volumes:
      - ./wallets:/app/wallets
      - ./config:/app/config
    environment:
      - PYTHONUNBUFFERED=1
    command: --help
    profiles:
      - cli
      - batch
      - interactive

  # Development service
  metawalletgen-dev:
    build: .
    image: metawalletgen/cli:dev
    container_name: metawalletgen-dev
    volumes:
      - .:/app
      - ./wallets:/app/wallets
      - ./config:/app/config
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    command: --help
    profiles:
      - dev
